name: Story-CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Test
        run: npm test --if-present

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

      - name: GSMC-front CI Discord Notification (success)
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.GSMC_FRONT_WEBHOOK }}
          title: "빌드 성공"
          status: ${{ job.status }}
          description: "성공 야르킁킁~~"
          color: 65280
          url: "https://github.com/sarisia/actions-status-discord"
          username: "gsmc-front-bot"

      - name: GSMC-front CI Discord Notification (failure)
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.GSMC_FRONT_WEBHOOK }}
          title: "빌드 실패"
          status: ${{ job.status }}
          description: "아으.... 이거 실패하너"
          color: 16711680
          url: "https://github.com/sarisia/actions-status-discord"
          username: "gsmc-front-bot"